package com.example.appointment.Database

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * Doctor
 * ------
 * This data class represents a single Doctor record in the database.
 * It’s annotated with @Entity so Room (Android’s database library)
 * can automatically create a SQLite table from it.
 *
 * The data class is also Serializable, allowing it to be passed easily
 * between activities using Intents.
 */
@Entity(tableName = "doctor_table")
data class Doctor(

    // Primary key (auto-generated by Room)
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // 🩺 Basic details
    val name: String = "",             // Doctor's full name
    val specialization: String = "",   // e.g., "Cardiologist"
    val address: String = "",          // Clinic or hospital address
    val location: String = "",         // Used for map or direction intent

    // ⭐ Additional information
    val rating: Double = 0.0,          // Average rating (e.g., 4.8)
    val year: String = "",             // Years of service (or graduation year)
    val patients: Int = 0,             // Number of patients served
    val experience: Int = 0,           // Years of experience
    val biography: String = "",        // Doctor’s bio or description

    // ☎️ Contact details
    val mobile: String = "",           // Phone number
    val site: String = "",             // Website or online profile link

    // 🖼️ Image details
    val picture: Int = 0,              // Default drawable image (from app resources)
    val imageUri: String? = null       // URI of an image picked from gallery (optional)
) : Serializable
